vaults: 
  example:
    full_path: '../example/vault_example'
    allowed_users: []
    home_file: 'readme.md'
    template_dir: templates
    base_config:
      error_on_field_parse: false
flask_params:
  port: 8000
  debug: true
  use_reloader: false
  host: 0.0.0.0
tasks:
  - cmd: echo "asd"
    interval: 30
    vault: example
    success: "Echo task for test (30 seconds)"